### ISSUE TITLE
mekanism crash revisited

### ISSUE THREAD

**Issue by Rynlwar** [Um-Mitternacht/Bewitchment#178] opened 2019-01-21 01:33 UTC
### Expected Behavior
launch normally

### Actual Behavior
crash on loading 

### Steps to Reproduce
start up mc

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
latest version of all requirements for bewitchment 1.12.2-0.0.17.7

### Logs, in the event of a crash
[crash-2019-01-20_20.08.42-client.txt](https://github.com/Um-Mitternacht/Bewitchment/files/2777292/crash-2019-01-20_20.08.42-client.txt)

**Comment by Sunconure11** [comment] 2019-01-22 03:53
@Orecruncher The issue is back, but I don't see where in the code this should be happening

**Comment by zabi94** [comment] 2019-01-22 11:07
line 37 of `com.bewitchment.common.item.block.ItemGemOre`, you're using `stack.getMetadata()`. You need to check if that is in the enum range before accessing the array, otherwise this crash happens.
Not sure why a metadata of 9 is on the stack, that should never happen given that the subtypes are 0 to 8, but there are other cases where a legit index is outside the range (like the ore dictionary metadata wildcard value).

**Comment by Sunconure11** [comment] 2019-01-22 20:38
I have no clue WTF is even happening in the code, regarding this issue. It should be fine, and also, this user isn't even using dynamic surroundings, and yet is running into it anyways.

**Comment by Sunconure11** [comment] 2019-01-23 00:03
@aidancbrady

Anything you spot that's wrong? I legitimately can't figure out what's wrong. There are 9 ores registered as gems (0 - 8, via metadata)

**Comment by Sunconure11** [comment] 2019-01-23 07:05
@Rynlwar If you are on the discord channel, you should be able to access a build that hopefully resolves this.

**Comment by Sunconure11** [comment] 2019-01-23 07:08
Seems to have been resolved in dev.

**Closed by Sunconure11** 2019-01-23 07:08 UTC
Labels: Compat/Integration, bug, excuse me but what the fuck
