### ISSUE TITLE
User reported error on servers

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#305] opened 2019-03-09 22:44 UTC
https://pastebin.com/raw/kX8vJc87

**Comment by itsmeow** [comment] 2019-03-09 22:58
Duplicate of #268

**Closed by itsmeow** 2019-03-09 22:58 UTC
Labels: MEDIUM, bug

**Comment by draeman8** [comment] 2019-03-13 01:16
i also had this crash :^)
you're great by the way i love you

**Comment by ghost** [comment] 2019-06-23 20:43
Our server still gets this crash
Is there a fix yet?

**Comment by Sunconure11** [comment] 2019-06-23 20:47
We're working on a rewrite, a lot of issues should be gone when it's out.
