### ISSUE TITLE
Cascading worldgen lag error

### ISSUE THREAD

**Issue by IITFA** [Um-Mitternacht/Bewitchment#471] opened 2019-12-19 01:41 UTC
### Expected Behavior
Spotted error in server console, probably shouldn't be an error.

### Steps to Reproduce
Was flying around in creative

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2
bewitchment-1.12.2-0.0.21.3.jar

### Logs, in the event of a crash
```
[20:31:54] [Server thread/WARN] [FML]: Bewitchment loaded a new chunk [47, 230] in dimension 0 (overworld) while populating chunk [48, 230], causing cascading worldgen lag.
[20:31:54] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[20:32:04] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 10330ms behind, skipping 206 tick(s)
```

**Comment by EnvyingGolem47** [comment] 2019-12-19 01:56
I'm not a developer nor do I understand Java code, but I can tell you that this happens with multiple mods such as Ruins, Thermal Expansion Mods, and any other mod that has something to generate in the world. This mainly just a minecraft limitation...

**Comment by Calanon7** [comment] 2019-12-21 04:58
I have noticed this issue since the beta.

**Comment by itsmeow** [comment] 2020-02-08 04:00
@EnvyingGolem47 Cascading worldgen lag is when a mod loads another chunk while generating. This is not, in it of itself a bad thing because some structures are multi-chunk. The problem is when the loading of this chunk loads yet another chunk and it continues. This is mostly caused by incorrect position offsets in generation of trees and flowers and such. You should not get "cascading worldgen lag" errors if a mod is doing things properly.

**Comment by Sunconure11** [comment] 2020-07-14 12:49
Due to how common this is with mods as a whole, closing.

**Closed as completed by Sunconure11** 2020-07-14 12:49 UTC
