### ISSUE TITLE
Broom stick dismounting and disapearing

### ISSUE THREAD

**Issue by Orncaex** [Um-Mitternacht/Bewitchment#489] opened 2020-01-15 02:38 UTC
### Expected Behavior 

Push shift, get off broomstick

### Actual Behavior

Push shift, stay on broomstick, unless you save and quit. Reloading can get you off the broom. And possibly lose the broomstick. Unclear if its location saved somewhere on the flight or if it got deleted

Broom also gets deleted if you are stuck on it and try to get onto or into something else like a bed, broomstick, and likely horse or boat. I have lost three broomsticks

### Steps to Reproduce

Juniper or Elder broomstick, fly around for a RANDOM distance (200+ meters) try to dismount. saving and quiting at any point after this got off the broomstick untill the time the broom was gone. Nothing other than useage seams to cause you to get stuck on the broom

### Version of 
Minecraft (1.12.2), 
Bewitchment (1.12.2-0.0.21.6), 
Forge(14.23.5.2847), 
Patchouli(1.0-20), 
Baubles(Baubles-1.12-1.5.2) 

### Screenshots encouraged
n/a

### Logs, in the event of a crash

no crash just loss of time and half a day walking back to my mud hut

**Comment by anqingchen** [comment] 2020-01-17 18:27
duplicate of #455

**Closed as completed by anqingchen** 2020-01-17 18:27 UTC
