### ISSUE TITLE
Game crashes when I delete gem bowl in creative

### ISSUE THREAD

**Issue by KlaiDain** [Um-Mitternacht/Bewitchment#332] opened 2019-04-07 15:22 UTC
### Expected Behavior
Not to crash

### Actual Behavior
Game crashes when I delete gem bowl in creative. Than after rejoining in the world where it happened world continues crashing
### Steps to Reproduce
Fix this issue

### Version of Minecraft, Bewitchment, Forge, Patchouli, LLibrary and Baubles used
1.12.2, 1.12.2-0.0.20.1_rewrite. 1.12.2-forge1.12.2-14.23.5.2825

### Logs, in the event of a crash
[crash-2019-04-07_17.46.37-server.txt](https://github.com/Um-Mitternacht/Bewitchment/files/3051663/crash-2019-04-07_17.46.37-server.txt)

**Comment by Sunconure11** [comment] 2019-04-07 16:23
Dupe of #331

**Closed** 2019-07-25 10:02 UTC
